# Generated by Django 5.2.6 on 2025-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KolamDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('original_image', models.ImageField(upload_to='kolam_images/')),
                ('analyzed_image', models.TextField(blank=True)),
                ('digitized_image', models.TextField(blank=True)),
                ('custom_grid_image', models.TextField(blank=True)),
                ('grid_size', models.IntegerField(default=5)),
                ('custom_grid_size', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
