# Generated by Django 5.2.6 on 2025-09-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KolamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('daily', 'Daily'), ('festival', 'Festival'), ('wedding', 'Wedding'), ('religious', 'Religious'), ('decorative', 'Decorative'), ('traditional', 'Traditional')], default='daily', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('pattern_data', models.JSONField()),
                ('preview_image', models.TextField(blank=True)),
                ('grid_size', models.IntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_data', models.JSONField()),
                ('preview_image', models.TextField(blank=True)),
                ('grid_size', models.IntegerField(default=5)),
                ('theme', models.CharField(default='traditional', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_theme', models.CharField(default='traditional', max_length=20)),
                ('default_grid_size', models.IntegerField(default=9)),
                ('line_thickness', models.IntegerField(default=2)),
                ('dot_size', models.IntegerField(default=3)),
                ('pattern_density', models.CharField(default='medium', max_length=20)),
                ('symmetry_type', models.CharField(default='radial', max_length=20)),
                ('auto_save', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
