# Generated by Django 5.2.6 on 2025-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolam', '0002_kolamtemplate_userpattern_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpattern',
            name='category',
            field=models.CharField(choices=[('generated', 'Generated'), ('digitized', 'Digitized'), ('favorites', 'Favorites')], default='generated', max_length=20),
        ),
    ]
